### ISSUE TITLE
getAllClasses gives false positives

### ISSUE THREAD

**Issue by chipshort** [jasononeil/compiletime#8]
With the following classes:
- abc.Test
- abcdeft.Example

When running:
```haxe
CompileTime.getAllClasses("abc");
```
both classes are in the result.

**Comment by jasononeil** [comment]
Thanks @chipshort  for reporting!  Just released a fix (was super simple, sorry I missed it earlier...)

Version 2.7.0 on haxelib has the fix

**Comment by chipshort** [comment]
@jasononeil No problem. Thanks for fixing and for this nice library.

**Comment by jasononeil** [comment]
I'm glad you've found it helpful! 😀
